#
# Copyright 2019 Ettus Research, A National Instruments Company
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

RFNOC_BLOCK_SCHEDULER_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/rfnoc/blocks/rfnoc_block_scheduler/, \
noc_shell_scheduler.v \
payloadDecoder.v \
scheduler.v \
rfnoc_block_scheduler.v \
))
